workflow:
    rules:
        - when: always

stages:
    - build
    - test
    - deploy

build_server:
    stage: build
    script:
        - echo "Build serveur"

build_electron:
    stage: build
    script:
        - echo "Should pass"
        - ./pipeline/pass.sh

cache:
    key: node
    when: always
    paths:
        - .npm/

test_server:
    stage: test
    allow_failure: true
    needs:
        - build_server
    script:
        - echo "Test server"
        - ./pipeline/test_server.sh
    

test_electron:
    stage: test
    allow_failure: true
    needs:
        - build_electron
    script:
        - echo "Test electron"
        - ./pipeline/test_electron.sh


deploy_dev:
    stage: deploy
    only:
        - develop
    script:
        - echo "Deploy dev"

deploy_prod:
    stage: deploy
    only:
        - master
    script:
        - echo "Deploy prod"
